### ISSUE TITLE
[Bug]: __netlify-handler function times out

### ISSUE THREAD

**Issue by Shubham510** [netlify/netlify-plugin-nextjs#1174]
### Summary

After upgrading from version 3.9 to 4.2.1, the site builds properly but after when visiting the page, it times out and gets a 502 error from the __netlify-handler function. It gives back the following error -

`{"errorMessage":"2022-01-28T15:53:17.566Z dcfe2e2a-53a5-44ef-a864-61fd6b598654 Task timed out after 10.01 seconds"}`

The same version of the code was working fine with the version 3.9. The logs for `__netlify-handler`  only show a timeout error and there is no other info which can be used for debugging.

### Steps to reproduce

.

### Plugin version

4.2.1

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[build]
    command = "npm run build"
    publish = ".next"

[context.production]
    environment = {NEXT_PUBLIC_API_URL=""}

[context.deploy-preview]
    environment = {NEXT_PUBLIC_API_URL=""}


[[plugins]] 
    package = "netlify-plugin-cypress"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
CYPRESS_CACHE_FOLDER = "../node_modules/.CypressBinary"
TERM = "xterm"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
8:09:12 PM 5e752d92 Duration: 10008.16 ms	Memory Usage: 275 MB	Init Duration: 186.18 ms
8:09:12 PM 5e752d92 ERROR  Task timed out after 10.01 seconds
8:09:21 PM 7b5ea894 Duration: 10007.95 ms	Memory Usage: 271 MB	Init Duration: 211.42 ms
8:09:21 PM 7b5ea894 ERROR  Task timed out after 10.01 seconds
8:51:25 PM e17c41f2 Duration: 10008.26 ms	Memory Usage: 271 MB	Init Duration: 229.31 ms
8:51:25 PM e17c41f2 ERROR  Task timed out after 10.01 seconds
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>
