### ISSUE TITLE
Website broken after upgrading to latest

### ISSUE THREAD

**Issue by leobenkel** [netlify/netlify-plugin-nextjs#1490]
Hello,

I switched from legacy version to the latest ones and I am having troubles.
I followed the migration. I removed my `_redirects` and instead used explicit config in `netlify.toml` . I also changed the `publish` to `.next`.
But now it looks like https://deploy-preview-14--purelambda.netlify.app/ instead of https://purelambda.com . All the CSS and JS seems gone. 

What did I do wrong and how to fix it ? 

PS: It works fine locally with `netlify dev` and `netlify build`. 

<details>
  <summary>My build settings</summary>

<img width="371" alt="Screen Shot 2022-07-26 at 12 48 41" src="https://user-images.githubusercontent.com/4960573/180988881-8262ac99-c69d-4a95-9bfe-3482bb0eb611.png">

</details>

<details>
  <summary markdown="1">package.json</summary>

```json
{
  "name": "learn-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "devDependencies": {
    "@lottiefiles/react-lottie-player": "^3.4.2",
    "@netlify/plugin-nextjs": "^4.12.2",
    "@netlify/plugin-sitemap": "^0.8.1",
    "ajv": "^8.11.0",
    "axios": "^0.21.1",
    "browserslist": "^4.21.2",
    "classnames": "^2.2.6",
    "feed": "^4.2.2",
    "isbot": "^3.3.4",
    "jquery": "^3.6.0",
    "jsdom": "^18.0.1",
    "lodash": "^4.17.21",
    "netlify-plugin-cache-nextjs": "^1.6.1",
    "netlify-plugin-inline-source": "^1.0.4",
    "netlify-plugin-minify-html": "^0.3.1",
    "next": "^10.0.0",
    "next-pwa": "^5.2.23",
    "postcss": "^8.3.0",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-preset-env": "^6.7.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-google-recaptcha": "^2.1.0",
    "react-intersection-observer": "^8.32.0",
    "react-jss": "^10.6.0",
    "react-onclickoutside": "^6.11.2",
    "react-svg": "14.0.0",
    "sass": "^1.34.1",
    "styled-jsx": "^4.0.1",
    "webpack": "^5.9.0"
  }
}
```

</details>

<details>
  <summary>next.config.js</summary>

```javascript
const withPWA = require('next-pwa')

module.exports = withPWA({
    pwa: {
        publicExcludes: [],
        cacheOnFrontEndNav: true,
        skipWaiting: false,
        register: false,
    },
    optimization: {
        minimize: true,
    }
})
```

</details>

<details>
  <summary>netlify.toml</summary>

```toml
[build]
    command = "npm run build"
    publish = ".next"
    functions = "functions"

[[plugins]]
package = "@netlify/plugin-sitemap"
# https://github.com/netlify-labs/netlify-plugin-sitemap
    [plugins.inputs]
    prettyURLs = true
    trailingSlash = false
    exclude = [
        '**/404*',
        '**/legalNotice*',
        '**/nda*',
        '**/privacyPolicy*',
    ]

[[plugins]]
# https://github.com/jonahsnider/netlify-cache-nextjs#readme
package = "netlify-plugin-cache-nextjs"

[[plugins]]
# https://github.com/philhawksworth/netlify-plugin-minify-html#readme
package = "netlify-plugin-minify-html"

    # Specify which deploy contexts we'll minify HTML in.
    # Supports any Deploy Contexts available in Netlify.
    # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
    [plugins.inputs]
    contexts = [
        'production',
        'branch-deploy',
        'deploy-preview'
    ]

    # Optionally, override the default options for the minification
    # https://github.com/kangax/html-minifier#options-quick-reference
    [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = true
    collapseWhitespace = true
    minifyCSS = true
    minifyJS = true
    sortAttributes = true
    sortClassName = true

# Redirects

[[redirects]]
from = "/root"
to = "/"
status = 301
force = false

[[redirects]]
from = "/home"
to = "/"
status = 301
force = false

[[redirects]]
from = "/blog"
query = {a = ":a"}
to = "/blog/:a"
status = 301
force = false

[[redirects]]
from = "/blog"
to = "/publicPresence"
status = 301
force = false
```

</details>

<details>
  <summary>jsconfig.json</summary>

```json
{
    "compilerOptions": {
        "baseUrl": "."
    }
}
```

</details>

<details>
  <summary>project structure</summary>

<img width="258" alt="Screen Shot 2022-07-26 at 12 57 07" src="https://user-images.githubusercontent.com/4960573/180990336-3802cd63-0160-4545-9344-03f84fd4ec81.png">

</details>

Thank you very much

**Comment by ascorbic** [comment]
Hey. Can you go to your site settings and disable all asset optimizations?

**Comment by leobenkel** [comment]
ok, done, it is rebuilding. 
I'll update here when it is done

**Comment by leobenkel** [comment]
ok it is working ! https://deploy-preview-14--purelambda.netlify.app/

but now my asset are not optimized ?

**Comment by ascorbic** [comment]
They are optimized by Next.js when the site is built, so you don't need the extra optimization

**Comment by leobenkel** [comment]
ok, sounds good. 

Since I have all my project structure and config up there. Can I ask an other question ? 

Locally it does work but not when deployed which is very frustrating.

I want the URL `/blog/?a=data-visualizations` to redirect with a 301 to `/blog/data-visualizations` .
I use 
```toml
[[redirects]]
from = "/blog"
query = {a = ":a"}
to = "/blog/:a"
status = 301
force = false
```
for it but i end up with a URL : `/blog/data-visualizations?a=data-visualizations`.

So I added :

```toml
[[redirects]]
from = "/blog/:id"
query = {a = ":a"}
to = "/.netlify/functions/redirects/?a=:id"
status = 301
force = false
```
before the previous rule in my `netlify.toml`

and here is the function:

```javascript
exports.handler = async (event, context) => {
    return {
        statusCode: 301,
        headers: {
            Location: '/blog/' + event.queryStringParameters.a,
            'Cache-Control': 'no-cache',
        }
    }
}
```

it does work locally, it drops the get query but not after deployment.

Any reason why ?

**Comment by nickytonline** [comment]
Hi @leobenkel! I don't think you need the explicit handler for redirects. This should be enough for what you're looking to accomplish. You can put this in your `[[redirects]]` section of your netlify.toml

```
/blog a=:a  /blog/:a  301
```

For more info on this, see https://docs.netlify.com/routing/redirects/redirect-options/#query-parameters

**Comment by leobenkel** [comment]
> Hi @leobenkel! I don't think you need the explicit handler for redirects. This should be enough for what you're looking to accomplish. You can put this in your `[[redirects]]` section of your netlify.toml
> 
> ```
> /blog a=:a  /blog/:a  301
> ```
> 
> For more info on this, see https://docs.netlify.com/routing/redirects/redirect-options/#query-parameters

This does not work. The resulted URL is `/blog/:a?a=:a` :( 

See other people having the same challenge: https://answers.netlify.com/t/redirect-doesnt-remove-query-params/31548

**Comment by nickytonline** [comment]
@leobenkel, you're right about it adding the query string still. My colleague @Hrishikesh-K made me aware that it didn't do this originally and then there was a big demand to have it put back. You can read about it more here, https://answers.netlify.com/t/23436.

Having said. that, you could probably accomplish this with an Edge function, e.g.

```javascript
export default (request) => {
  const { searchParams, href, pathname } = new URL(request.url)

  if (!searchParams.has('a')) {
    return
  }

  const a = searchParams.get('a');

  const redirectUrl = new URL(href.replace(pathname, `/blog/${a}`).replace(/\?a=.*/, '')).toString()
  console.log(redirectUrl)

  return Response.redirect(redirectUrl, 302);
}
```

Here's an example repo https://github.com/nickytonline/nextjs-plugin-1490

**Comment by leobenkel** [comment]
> @leobenkel, you're right about it adding the query string still. My colleague @Hrishikesh-K made me aware that it didn't do this originally and then there was a big demand to have it put back. You can read about it more here, https://answers.netlify.com/t/23436.
> 
> Having said. that, you could probably accomplish this with an Edge function, e.g.
> 
> ```js
> export default (request) => {
>   const { searchParams, href, pathname } = new URL(request.url)
> 
>   if (!searchParams.has('a')) {
>     return
>   }
> 
>   const a = searchParams.get('a');
> 
>   const redirectUrl = new URL(href.replace(pathname, `/blog/${a}`).replace(/\?.*/, '')).toString()
>   console.log(redirectUrl)
> 
>   return Response.redirect(redirectUrl, 302);
> }
> ```
> 
> Here's an example repo, https://github.com/nickytonline/nextjs-plugin-1490 and you can test it out at https://edge-function-redirect.netlify.app/

thank you for your help, looking at the documentation it seems that edge functions are still in beta (https://docs.netlify.com/netlify-labs/experimental-features/edge-functions/). Would it be possible to do the same thing using the classic functions ? 

The one i had was :

```javascript
exports.handler = async (event, context) => {
    return {
        statusCode: 301,
        headers: {
            Location: '/blog/' + event.queryStringParameters.a,
            'Cache-Control': 'no-cache',
        }
    }
}
```

with 

```toml
[[redirects]]
from = "/blog/:id"
query = {a = ":a"}
to = "/.netlify/functions/redirects/?a=:id"
status = 301
force = false

[[redirects]]
from = "/blog"
query = {a = ":a"}
to = "/blog/:a"
status = 301
force = false

[[redirects]]
from = "/blog"
to = "/publicPresence"
status = 301
force = false
```

Thank you
