### ISSUE TITLE
[Bug]: Edge Middleware Functions don't share code, resulting in large bundle sizes

### ISSUE THREAD

**Issue by Skn0tt** [netlify/netlify-plugin-nextjs#1504]
### Summary

At the moment, the plugin emits a huge `bundle.js` file into each of the edge function directories, e.g. `.netlify/edge-functions/next_pages_item/bundle.js` and `.netlify/edge-functions/next_pages_slow/bundle.js`. These files are very big (lots of Next.js source code), but are identical. The bundling process doesn't know they're the same, though, and will include each of these bundles in their own namespace, resulting in very big bundles.

We could lower the bundle size by moving the `bundle.js` file one level up, to `.netlify/edge-functions/__next_bundle.js`. As long as it doesn't occur in the edge functions declarations, it won't be bundled.

### Steps to reproduce

1. Clone https://github.com/netlify/next-react-server-components
2. Run `ntl build --offline`
3. Check the bundle in `.netlify/edge-functions-dist/`, it will contain the same code four times (because four edge functions are generated)

### A link to a reproduction repository

https://github.com/netlify/next-react-server-components

### Plugin version

^4.13.1

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[build]
command = "next build"
base = "."
publish = ".next"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[functions]
included_files = [
  "!node_modules/sharp/vendor/8.12.2/darwin-*/**/*",
  "!node_modules/sharp/build/Release/sharp-darwin-*"
]
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
module.exports = {
  experimental: {
    runtime: 'experimental-edge',
    serverComponents: true,
  },
}
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>
