### ISSUE TITLE
_headers ignored in getServerSideProps

### ISSUE THREAD

**Issue by samiahmedsiddiqui** [netlify/netlify-plugin-nextjs#397]
**Describe the bug**
I have set headers from `_headers` file and it works well on the static assets but it doesn't work with pages created with **getServerSideProps**.

Here is the `_headers` file content:

```yml
/*
  # http security headers
  Strict-Transport-Security: max-age=63072000; includeSubDomains
  Cache-Control: max-age=31536000
  x-frame-options: SAMEORIGIN
  x-content-type-options: nosniff
  x-xss-protection: 1; mode=block
  referrer-policy: no-referrer-when-downgrade
  Access-Control-Allow-Origin: *
``` 

On Netlify Dashboard, I can see the message that "All header rules deployed without errors." and If I add HTTP Auth in this file then it starts working so the issue only belongs to the SSR pages.

I have also tried by configuring the headers from the `netlify.toml` and that also doesn't work. I have also tried to override the headers by using `next.config.js` which works well locally but doesn't with Netlify.

**Versions**
- Next.js: 10.2.3

**If you're using file-based installation**
- netlify.toml:
  ```yml
  [build]
    functions = "functions"
    # Default build command.
    command = "npm run build"

  [[plugins]]
    package = "@netlify/plugin-nextjs"

  [[plugins]]
    package = "netlify-plugin-cache-nextjs"
  ```
