### ISSUE TITLE
[Bug]: ESM not supported with Netlify functions?

### ISSUE THREAD

**Issue by FabienMotte** [netlify/netlify-plugin-nextjs#750]
### Steps to reproduce

Hello!

I've an error in the Netlify function `___netlify-handler` complaining about `exports` not being defined for a node module.
Looks like Netlify functions are using a Node.js version that don't supports ESM, am I right?
Starting with Next.js 12, ESM are supported out of the box, am I missing something?

Thank you!

### A link to a reproduction repository

https://github.com/algolia/pwa-storefront-ui-template/pull/33

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Mac OS

### Your `netlify.toml` file

```toml
[build]
  command = "npm run build"
  publish = ".next" 

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

  [[plugins.inputs.audits]]
    path = "./"
```

### Relevant log output (or link to your logs)

```text
6:19:59 PM f3a6a33f ERROR  ReferenceError: exports is not defined
    at file:///var/task/node_modules/@algolia/react-instantsearch-widget-loadmore-with-progressbar/dist/index.es.js:24:10
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
6:19:59 PM f3a6a33f ERROR  Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ReferenceError: exports is not defined","reason":{"errorType":"ReferenceError","errorMessage":"exports is not defined","stack":["ReferenceError: exports is not defined","    at file:///var/task/node_modules/@algolia/react-instantsearch-widget-loadmore-with-progressbar/dist/index.es.js:24:10","    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)","    at async Loader.import (internal/modules/esm/loader.js:182:24)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: ReferenceError: exports is not defined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
6:19:59 PM f3a6a33f Duration: 924.22 ms	Memory Usage: 100 MB	Init Duration: 458.17 ms
```
